# Checkov Configuration
# Checkov is a static code analysis tool for Infrastructure as Code
# It scans Terraform, Kubernetes, Docker, and more for security and compliance issues
# Install: pip install checkov
# Run: checkov -d .

framework:
  - terraform
  - dockerfile
  - docker_compose
  - kubernetes
  - helm

# Skip checks (optional - adjust based on your needs)
skip-check:
  # Skip checks that require actual cloud credentials
  - CKV_AWS_*
  - CKV_GCP_*
  - CKV_AZURE_*
  
  # Skip checks that might be too strict for learning environments
  # Uncomment if you want to skip specific checks:
  # - CKV_DOCKER_2  # Ensure that HEALTHCHECK instructions have been added to container images
  # - CKV_DOCKER_3  # Ensure that a user for the container has been created

# Output formats
output:
  - cli
  - json
  - junitxml

# Include/exclude files
soft-fail: false  # Fail on any security issue found

# Minimum severity level to report
min-severity: MEDIUM  # Options: INFO, LOW, MEDIUM, HIGH, CRITICAL

# Quiet mode (less verbose output)
quiet: false

# Show summary
compact: false

# External checks directory (optional)
external-checks-dir: null

# External checks Git (optional)
external-checks-git: null

# Guidelines
guidelines:
  - bridgecrew  # Use Bridgecrew security guidelines

